### PR TITLE
Enable Travis CI for testing

### PR DESCRIPTION
**Pull request by dhimmel**
@publicus can you review this.

The purpose is to use TravisCI to automate the testing. This way if a PR breaks the environment or tests, we'll know it.

### CODE REVIEW

**Review by jglev — COMMENTED** [review]
Everything here looks good to me.

I haven't set up Travis before, but what you've put together looks sensible to me after reading the documentation.

One thing to confirm: Do we need to add `.` to the `PATH` / `PYTHONPATH` to the Travis setup? (I need to use `PYTHONPATH=.` when running the download script from the command line, so I'm asking here.)

The edits to the Readme read well to me. And `@pytest.mark.parametrize` is cool! I hadn't seen that before.

**Comment by jglev** [comment]
I'll click Approve on this as soon as you confirm the one question I brought up.

**Comment by dhimmel** [comment]
CI is nice because it makes it easy to catch things like the environment issue from #10 (see the corresponding [build failure](https://travis-ci.org/greenelab/library-access/builds/296343355#L678)).

> Do we need to add . to the PATH / PYTHONPATH to the Travis setup?

At the moment this isn't required for the existing tests. I'm not sure modifying your `PATH` is the right solution. We should try to make it so you can run your commands from the repo and they work based on relative links.

Perhaps save this issue for another PR that actually runs the scripts?

**Comment by jglev** [comment]
Sure!

**Comment by jglev** [comment]
I don't see a button at this point to do an official "Approve" step for review. To clarify, should I be seeing that, or can you just merge at this point?

**Comment by dhimmel** [comment]
> I don't see a button at this point to do an official "Approve" step for review. To clarify, should I be seeing that, or can you just merge at this point?

Under files changed, click review changes. Then you can select Approve. I can merge now, but might as well get the official approval as best practice.

**Review by jglev — APPROVED** [review]

**Comment by jglev** [comment]
Thanks!

**Pull request merged**
