### PR TITLE
Confidence intervals for PennText accuracies

### PR DESCRIPTION
**Pull request by dhimmel**
Same approach as https://github.com/greenelab/scihub/pull/50. Uses [Jeffreys method](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Jeffreys_interval) for binomial proportion confidence intervals.

### CODE REVIEW

**Comment by dhimmel** [comment]
@publicus any PR feedback will be addressed in a subsequent PR.

**Comment by jglev** [comment]
Great! I look forward to looking through these changes; I'll do so tomorrow!

**Comment by dhimmel** [comment]
Okay, we're hoping to resubmit the paper ASAP... potentially today or tomorrow so sooner the better.

**Comment by jglev** [comment]
Just a note for future readers that I've just now left a comment on this [here](https://github.com/greenelab/scihub-manuscript/pull/49#issuecomment-362321351).

**Pull request merged**
