### PR TITLE
Adding ex libris alma downloader for upenn holdings

### PR DESCRIPTION
**Pull request by publicus**
This is an in-progress PR (i.e., not to be actually merged yet). Following the discussion in #1, it adds the following:

- Data:
    - The `state-of-oa-dois` dataset from @dhimmel [in this comment](https://github.com/greenelab/library-access/issues/1#issuecomment-331969935).
            - An updated version of this dataset with a new binary (`1`/`0` = `true`/`false`) column indicating which DOIs are digitally accessible in full text from UPenn.
    - Downloaded XML files (for now, a sample) from the Alma API.
- Scripts:
    - A downloader script (written in Bash) for acquiring the XML files that indicate whether full text is digitally available.
    - An XML parser script (written in Python) for taking the downloaded XML files and using them to update the dataset's `upenn_has_full_text` column.
    - An example analysis script (written in R) for taking the dataset's `upenn_has_full_text` column and, from it, calculating a Bayesian 95% Credible Interval on the estimate of the "true" rate of full-text access to DOIs of this type.

### CODE REVIEW

**Comment by publicus** [comment]
One important note about this dataset: It only indicates that full-text is available if it is *digitally* available. Put differently, it does *not* reflect whether a patron could physically go to a library shelf and get a hard copy of an article. This matches @dhimmel's original specification when we talked about it, but is nonetheless something I want to be clear about.

An example of this: For DOI `10.1001/archderm.1924.02360250152011`:

[PennText](https://upenn.alma.exlibrisgroup.com/discovery/openurl?institution=01UPENN_INST&vid=01UPENN_INST:Services&ctx_ver=Z39.88-2004&rft.genre=article&ctx_enc=info:ofi%2Fenc:UTF-8&url_ver=Z39.88-2004&url_ctx_fmt=infofi%2Ffmt:kev:mtx:ctx&rfr_id=info:sid%2Fprimo.exlibrisgroup.com:primo4-article-cLinker&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:article&isCitationLinker=Y&rft.date=&rft_id=info:doi%2F10.1001%2Farchderm.1924.02360250152011&rft.atitle=&rft.jtitle=&rft.volume=&rft.issue=&rft.spage=&rft.epage=&rft.issn=&rft.doi=10.1001%2Farchderm.1924.02360250152011&rft.pmid=&rft.aulast=&rft.aufirst=&rft.auinit=&rft.publisher=&rft.pubdate=) shows that full text *is* available in print, just not digitally. However, the [XML](https://github.com/publicus/library-access/blob/adding_ex_libris_alma_downloader_for_upenn_holdings/Datasets/State_of_OA/Ex_Libris_Alma_Downloaded_XML_Files/10.1001%252Farchderm.1924.02360250152011) indicates that full-text is *not* available (see the `full_text_indicator` key).

Second, I've assumed in my query script that these DOIs are all for articles. Is that correct?

**Comment by publicus** [comment]
I'm fixing something in my Git repo., so the PR linked repo. isn't present at the moment. I'll fix that momentarily.

**Comment by dhimmel** [comment]
> One important note about this dataset: It only indicates that full-text is available if it is *digitally* available.

Great!

> Second, I've assumed in my query script that these DOIs are all for articles. Is that correct?

They should mostly be articles, although what do you mean by articles? Some of them could be book chapters. Maybe even a few could be entire books. What will happen if the type is wrong? Article is the best default type.

For our complete Crossref catalog with XX DOIs, these DOIs will all be article-like (see https://github.com/greenelab/scihub/issues/7).

**Comment by dhimmel** [comment]
> I'm fixing something in my Git repo., so the PR linked repo. isn't present at the moment. I'll fix that momentarily.

In the next PR, don't track the raw XML files... that will become unsustainable quickly.

**Pull request closed without merging**
